# Generated by Django 2.2.2 on 2020-08-24 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Ambiente')),
                ('slug', models.SlugField(help_text='Preenchido automaticamente, não editar.', max_length=100, unique=True, verbose_name='Identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Artista')),
                ('biografia', models.CharField(max_length=100, verbose_name='Ambiente')),
                ('slug', models.SlugField(help_text='Preenchido automaticamente, não editar.', max_length=100, unique=True, verbose_name='Identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(help_text='Preenchido automaticamente, não editar.', max_length=100, unique=True, verbose_name='Identificador')),
                ('profissao', models.CharField(max_length=100, verbose_name='Profissão')),
                ('idade', models.CharField(max_length=3, verbose_name='Idade')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('contato', models.CharField(max_length=100, verbose_name='Contato')),
                ('data_do_termo', models.DateField(max_length=100, verbose_name='Data do termo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipodeArtefato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo de artefato')),
                ('slug', models.SlugField(help_text='Preenchido automaticamente, não editar.', max_length=100, unique=True, verbose_name='Identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Artefato',
                'verbose_name_plural': 'Artefatos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipodeEntrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo de Entrada')),
                ('slug', models.SlugField(help_text='Preenchido automaticamente, não editar.', max_length=100, unique=True, verbose_name='Identificador')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Materiais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Preenchido automaticamente, não editar.', max_length=100, unique=True, verbose_name='Identificador')),
                ('codigo_registro', models.CharField(max_length=7, unique=True, verbose_name='Código Registro')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.CharField(max_length=100, verbose_name='Decrição')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura')),
                ('largura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Largura')),
                ('outras', models.CharField(max_length=100, verbose_name='Outras')),
                ('data_da_conclusao', models.DateField(verbose_name='Data da conclusão da peça')),
                ('local', models.CharField(max_length=100, verbose_name='Local')),
                ('tecnica', models.CharField(max_length=100, verbose_name='Técnica')),
                ('suporte', models.CharField(max_length=100, verbose_name='Suporte')),
                ('moldura', models.CharField(max_length=100, verbose_name='Moldura')),
                ('valor_estimado_original', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Estimado Original (R$)')),
                ('ultimo_valor_estimado', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Último Valor Estimado (R$)')),
                ('data_ultimo_valor_estimado', models.DateField(verbose_name='Data do último valor estimado')),
                ('posicao_assinatura', models.CharField(max_length=100, verbose_name='posição da assinatura')),
                ('historico_do_artefato', models.CharField(max_length=100, verbose_name='Histórico do artefato')),
                ('coletor', models.CharField(max_length=100, verbose_name='Coletor')),
                ('data_da_catalogacao', models.DateField(verbose_name='Data da catalogação')),
                ('catalogador', models.CharField(max_length=100, verbose_name='Catalogador')),
                ('image', models.URLField(max_length=800, verbose_name='Imagem')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.Ambiente', verbose_name='Ambientes')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.Artista', verbose_name='Artistas')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.Colaborador', verbose_name='Colaboradores')),
                ('tipo_de_artefato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.TipodeArtefato', verbose_name='Artefatos')),
                ('tipo_de_entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.TipodeEntrada', verbose_name='Entradas')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'ordering': ['codigo_registro'],
            },
        ),
    ]
