# Generated by Django 2.2.2 on 2020-08-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20200824_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiais',
            name='data_ultimo_valor_estimado',
            field=models.DateField(blank=True, null=True, verbose_name='Data do último valor estimado'),
        ),
        migrations.AlterField(
            model_name='materiais',
            name='posicao_assinatura',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='posição da assinatura'),
        ),
    ]
