# Generated by Django 2.2.2 on 2020-08-24 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20200824_1848'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Materiais',
            new_name='Material',
        ),
    ]
