# Generated by Django 2.2.2 on 2020-08-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20200824_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='procedencia',
            field=models.TextField(default='', max_length=200, verbose_name='Procedência:'),
        ),
        migrations.AlterField(
            model_name='material',
            name='descricao',
            field=models.TextField(max_length=200, verbose_name='Decrição'),
        ),
    ]
