# Generated by Django 2.2.2 on 2020-08-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20200824_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colab', to='catalogo.Colaborador', verbose_name='Colaboradores'),
        ),
    ]
