# Generated by Django 2.2.2 on 2020-08-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20200825_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.FileField(default='', max_length=800, upload_to='', verbose_name='Imagem'),
        ),
    ]
