# Generated by Django 2.2.2 on 2020-08-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20200829_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.URLField(max_length=800, verbose_name='Imagem'),
        ),
    ]
